apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicdpipeline
  labels:
    app: cicdpipeline
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cicdpipeline
  template:
    metadata:
      labels:
        app: cicdpipeline
    spec:
      containers:
      - name: cicdpipeline
        image: vaidikprabhu/pipeline-demo
        ports:
        - containerPort: 80
