apiVersion: v1
kind: Service
metadata:
  name: cicdpipeline
  labels:
    app: cicdpipeline
spec:
  selector:
    app: cicdpipeline
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 80
      nodePort: 31200
