apiVersion: v1
kind: Service
metadata:
  name: cicdpipeline
spec:
  type: NodePort
  selector:
    app: cicdpipeline
  ports:
  - protocol: TCP
    port: 80         # This should match the application's listening port
    targetPort: 80   # This should also match the application's listening port
    nodePort: 31200  # Optional: Set NodePort explicitly if required
